server:
    # 服务端口
    port: 9999
    # 服务路径
    contextPath:
    # tomcat最大连接数
    tomcat.max-connections: 1024
    # tomcat最大线程数
    tomcat.max-threads: 1024

# LOG相关设置
logging:
    path: /var/log/netty-demo
    level:
        com.liuwei: TRACE
        org.springframework: WARN
        io.netty: DEBUG

#Netty设置
netty:
    socket:
        host: 0.0.0.0
        port: 1888
        timeout: 120
    keepalived.timeout: 70